# This workflow runs Rust tests and checks on push and pull request events
name: Rust Testing

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    needs: ["check"]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependecies on Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Dependencies on MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install protobuf

      - name: Install Dependencies on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install protoc
          choco install nasm
          echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Test Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  check:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Install Rust fmt
        run: rustup component add rustfmt
      - name: Install Rust clippy
        run: rustup component add clippy
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

